# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook
markdown: kramdown
syntax_highlighter_style: colorful
toc:
    enabled: true
    h_min: 1
    h_max: 3
webrick:
  headers:
    My-Header: 杀戮尖塔模组加载器第三方指南
    My-Other-Header: 加载器指南
